<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Price639_Baltimore</name>
   <tag></tag>
   <elementGuidId>323516c2-39ea-4a65-858f-0e96285f9420</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vrgf-price-box__price ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            $
            639*
            Avg PP
          </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccl-refresh-homepage&quot;)/div[@class=&quot;grid&quot;]/div[@class=&quot;row-1-wrap&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-1-1&quot;]/div[@class=&quot;ccs-host ccs-host--landing-page ng-scope&quot;]/ccl-cruise-search[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;ccs-container ccs-container--always-sticky&quot;]/ccl-view-result-container[@class=&quot;ccs-search-results ng-scope ng-isolate-scope&quot;]/div[@class=&quot;vrcn-wrapper vrcn-wrapper--centered&quot;]/ccl-view-result-grid[@class=&quot;ng-scope ng-isolate-scope&quot;]/article[@class=&quot;vrg-result-item ng-scope vrg-result-item--result vrg-result-item--small&quot;]/ccl-view-result-grid-item[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;vrg-search-unit&quot;]/div[@class=&quot;vrg-pricing-footer&quot;]/ccl-view-result-grid-footer[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;vrgf-wrapper&quot;]/div[@class=&quot;vrgf-button-wrapper&quot;]/div[@class=&quot;vrgf-price-box&quot;]/div[@class=&quot;vrgf-price-box__wrapper&quot;]/p[@class=&quot;vrgf-price-box__price-info&quot;]/span[@class=&quot;vrgf-price-box__price ng-binding&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ccl-refresh-homepage']/div/div/div/div/div/ccl-cruise-search/div[3]/ccl-view-result-container/div/ccl-view-result-grid/article/ccl-view-result-grid-item/div/div/ccl-view-result-grid-footer/div/div/div[2]/div/p[2]/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dates'])[2]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='639']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
